### ISSUE TITLE
reattach takes forever (only partial reattachment)

### ISSUE THREAD

**Issue by lepinekong** [renancamm/figma-reattache-instance#12]
I have a case where reattach takes forever see gif anime and figma file.
![Reattach-Instance-Bug-02](https://user-images.githubusercontent.com/5175342/72028503-0b4e3200-3283-11ea-9097-bc8a6651b5ab.gif)

**Comment by lepinekong** [comment]
I think I found a culprit: weirdly it cannot even attach a component when there is even a single line whereas it works with a rectangle.

**Comment by renancamm** [comment]
@lepinekong Do you know how to fix it?

**Comment by lepinekong** [comment]
@renancamm  I'm reading the source code trying to understand how it works for now :^)

**Comment by glebsexy** [comment]
I don't know what the issue is here, but I know it doesn't happen with my [Master](https://www.figma.com/c/plugin/767721682134156281/Master) plugin (paid, with a free trial), a part of code from which is contributed to this repository (but it was greatly improved afterwards). It works a bit differently and you can attach an object to component in two steps:

1. Select one Instance or Master Component. Run “Save or Attach to Saved Master” command, the plugin will remember selected Component.
2. Select any number of other objects (but you need at least two if they are Instances) you want to turn into Instances of the saved Component.
3. Run the same command (Alt + Cmd/Ctrl + P if in the same file).
4. All objects will be replaced with Instances of the previously selected Component, keeping overrides where possible.

It's made this way so unlike Reattach instance it doesn't search the whole file for components which could take forever on large files. Also works with Team Libraries so you can move components between files. Hope it helps and let me know if you have any questions!

**Comment by lepinekong** [comment]
@zyumbik thanks a lot for your instructions, that should help. I'm creating a kit for french students as you know most are poor so they can only use free plugin so I'll try to debug but that's weird it works with all shapes except lines theorically that shouldn't be a special case ;) 

Your paid plugin is interesting also, I'll probably buy it.

**Comment by glebsexy** [comment]
@lepinekong if by any chance a generous discount for students would help, I would be happy to provide it, especially if it would be a bulk purchase.

Yeah, that sounds super weird. Are you sure it's the lines that are stopping the plugin? I fixed about 20 bugs in Master and none were related to lines. Wait, actually one was! It was caused by the fact that lines have 0 height and you can't assign height of 0 to any objects.

**Comment by lepinekong** [comment]
@zyumbik I don't have 0 height and it's even crazier than I thought: in some cases it works in other cases it takes forever whereas I can see no difference have joined the file :)
![reattach-lines](https://user-images.githubusercontent.com/5175342/73357743-574a3080-429d-11ea-84a0-0d7dae6a8653.gif)
[reattach-lines.zip](https://github.com/renancamm/figma-reattache-instance/files/4127991/reattach-lines.zip)

**Comment by glebsexy** [comment]
@lepinekong well, lines do have the height of 0. But it doesn't mean it's the cause of the problem, it's just one of the things I had to fix in Master, otherwise it crashed. I think the issue here could be in the search algorithm though. This is the only part of code which could take forever to do I believe.

**Comment by lepinekong** [comment]
@zyumbik oops didn't realize I did set to 0 because it wasn't on purpose I thought it was 0.5 or did I on purpose I don't remember why :)
Now found an other case this time on a rectangle and which not 0 on w or h:
![reattach-instance](https://user-images.githubusercontent.com/5175342/73377172-e9aefc00-42be-11ea-99e1-9828cdc73c4c.png)
[reattach-instance.zip](https://github.com/renancamm/figma-reattache-instance/files/4129260/reattach-instance.zip)

I cannot reattach border:right/0

**Comment by lepinekong** [comment]
> @lepinekong well, lines do have the height of 0. But it doesn't mean it's the cause of the problem, it's just one of the things I had to fix in Master, otherwise it crashed. I think the issue here could be in the search algorithm though. This is the only part of code which could take forever to do I believe.

confirm it was due to h=0, I set to 0.5 I can reattach

**Comment by lepinekong** [comment]
@zyumbik found why for the other case: I have an empty text field (this was on purpose) so will use a space instead ;)

Thanks.

**Comment by lepinekong** [comment]
I will close issue as it is minor finally.
